### ISSUE TITLE
#001 comment sizes are strictly limited

### ISSUE THREAD

**Issue by AlexErdei73** [JonathanDPotter/howler#1]
Congratulations to howler, I like the site, because it's basic functionality is working well, not like so many others, which I tried on TOP. The issue, which I mention here is not a huge one. I can post more comments so it is not crazy important to give more space to text content, but it would be nice. How is it with the original app? It would be certainly better if the input field were able to give more space to text maybe with following the actual size of the text, which has been typed in.

**Comment by JonathanDPotter** [comment]
The Howl and Comment character limits mimic the character limits of Twitter.  The limit is not a bug, but a feature.  I will look at re-styling the comment input to be larger instead of a single line like it is now.
